# Generated by Django 5.2.8 on 2025-11-11 04:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PublicItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('api_id', models.CharField(max_length=100, unique=True)),
                ('item_type', models.CharField(choices=[('movie', 'Movie'), ('series', 'Series'), ('anime', 'Anime'), ('book', 'Book'), ('music', 'Music')], max_length=10)),
                ('title', models.CharField(max_length=255)),
                ('poster_url', models.URLField(blank=True, max_length=1024, null=True)),
                ('release_date', models.DateField(blank=True, null=True)),
                ('total_episodes', models.IntegerField(blank=True, null=True)),
                ('total_chapters', models.IntegerField(blank=True, null=True)),
                ('author', models.CharField(blank=True, max_length=255, null=True)),
                ('publisher', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserLibrary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('watching', 'Watching'), ('planned', 'Planned'), ('completed', 'Completed'), ('paused', 'Paused'), ('dropped', 'Dropped')], default='planned', max_length=10)),
                ('progress', models.IntegerField(default=0)),
                ('rating', models.IntegerField(blank=True, null=True)),
                ('review', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_entries', to='api.publicitem')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='library_items', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'User Libraries',
                'unique_together': {('user', 'item')},
            },
        ),
    ]
